socialhand/src/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),

]

socialhand/src/shop/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import  ProductListView

urlpatterns = [
 
	url(r'^productos/$', ProductListView.as_view(), name='product_list'),
	url(r'^productos/(?P<slug>[-\w]+)/$',ProductListView.as_view(),name='product_list_by_category'),
	url(r'^productos/(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.product_detail,name='product_detail'),
	url(r'^productos/(?P<id>\d+)/(?P<slug>[-\w]+)/edit/$', views.product_edit, name='product_edit'),
	url(r'^productos/(?P<id>\d+)/(?P<slug>[-\w]+)/remove/$',views.product_remove, name='product_remove'),
	url(r'^ranking/$', views.product_ranking, name='create'),
	# paginacion alternativa no definitiva
	url(r'^auto/$', ProductListView.as_view()),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialhand/src/socialhand/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import shop.urls
from search import views as search_views
from . import views
# from .views import notes
from django.views.generic import TemplateView



urlpatterns =  [
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^', include(shop.urls, namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    # url(r'^search/', views.notes, name='search'),
    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    # Home URL
    url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),
    # Logout URL for social Auth
    url(r'^users/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="user-logout"),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^contact/$',views.contact, name='contact'),
    url(r'^api/',include('socialhand.api.urls',namespace='api')),
    

]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialhand/src/shop/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True, unique=True)

	class Meta: 
		ordering = ('name',)
		verbose_name = ('category')
		verbose_name_plural = ('categories')

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_category',args=[self.slug])

class Product(models.Model):
	author = models.ForeignKey('authtools.User', null=True)
	category = models.ForeignKey(Category,related_name='products')
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True)
	image = models.ImageField( upload_to='products/%Y-%m-%d',null=True,blank=True)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	stock = models.PositiveIntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_detail',args=[self.id, self.slug])

	def save(self, *args, **kwargs):
            try:
                this = Product.objects.get(id=self.id)
                if this.image != self.image:
                    this.image.delete()
            except: pass
            super(Product, self).save(*args, **kwargs)

socialhand/src/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from profiles.forms import ShopFor
from django.shortcuts import redirect
from profiles.views import ShowProfile
from profiles.models import Profile
from django.views.generic import TemplateView,View,DetailView
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic.list import ListView
from django.views.generic.base import ContextMixin
# para el-pagination 
from el_pagination.views import AjaxListView
# import redis

# connect to redis
# r = redis.StrictRedis(host='localhost', port=6379, db=0)

  
def product_list(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)
	# products = Product.objects.filter(author=request.user).order_by('?')
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = products.filter(category=category)
	return render(request,
				'shop/product/list.html',
				{'category'	: category,
				'categories': categories,
				'products': products})

def product_detail(request, id, slug):
	product = get_object_or_404(Product,
								id=id,
								slug=slug,
								available=True)
	# increment total image views by 1
	# total_views = r.incr('product:{}:views'.format(product.id))
	# increment image ranking by 1
	# r.zincrby('product_ranking', product.id, 1)
	cart_form = CartAddProductForm()
	# looking author of product
	creator=product.author
	if creator :
		craftsman = get_object_or_404 (Profile,user_id=creator)																			
	return render(request,
				 'shop/product/detail.html',{
				 'product': product,
				 # 'total_views':total_views,
				 'cart_form': cart_form,
				 'craftsman':craftsman,})
	 
def product_edit(request,id,slug):
        product = get_object_or_404(Product,
                                    id=id,
                                   	slug=slug)                            	
        if request.method == "POST":
            form = ShopFor(request.POST,request.FILES or None, instance=product)
            if form.is_valid():
                product = form.save (commit=False)
                product.author = request.user
                product.save()
                return redirect("profiles:show_self")
        else:
            form = ShopFor (instance=product)
        return render(request, 'profiles/product_add.html', {'form':form})

def product_remove (request,id,slug):
		product = get_object_or_404(Product,
									id=id,
									slug=slug)
		user =request.user
		if product.author == user:
			product.delete()
		return redirect ('profiles:show_self')	
#considerar otra vista para redirecionar en lugar de show_self

def product_ranking(request):
		# get image ranking dictionary
		product_ranking = r.zrange('product_ranking', 0, -1,desc=True)[:10]
		product_ranking_ids = [int(id) for id in product_ranking]
		# get most viewed images
		most_viewed = list(Product.objects.filter(id__in=product_ranking_ids))
		most_viewed.sort(key=lambda x: product_ranking_ids.index(x.id))
		return render(request,
					'shop/product/ranking.html',
					{'section': 'products',
					'most_viewed': most_viewed})


class ProductListView(AjaxListView):
		context_object_name= 'products'	
		template_name = "shop/product/list.html"
		page_template = "shop/product_list.html"
		
		def get_queryset(self):
			return Product.objects.all()
			
		def get_context_data(self,**kwargs):
			category = None
			slug = self.kwargs.get('slug')
			products = Product.objects.all()
			categories = Category.objects.all()
			kwargs['categories']= categories
			if  slug:
				category = get_object_or_404(Category, slug=slug)
				products =products.filter(category=category)				
			kwargs['products'] = products
			kwargs['category'] = category
			return super(ProductListView,self).get_context_data(**kwargs)

socialhand/src/shop/templates/shop/product/detail.html
{% extends "shop/home.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
	{% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}


{% block container %}
<br><br>
<div id="detail"class="justified-gallery" style="background-color: black;">  
	<div>
		<img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "image/noimage.png" %}{% endif %}"  alt="<h3 class='text-center'>{{product.name}} </br>${{ product.price }}</h3>">		
	</div>
</div> 
<div class="container-fluid"> 
</br> 
	 {% if product.author == user %}
	 <div class="col-md-4" style="float: left;">
	 	<a class="btn btn-primary"  href="{% url 'shop:product_edit' product.id product.slug %}"><span class="glyphicon glyphicon-pencil"></span></a>	
	 	<!-- first -->
	 	<button type="button" class="btn btn-primary" data-toggle="popover"  data-trigger="focus" data-placement="right" data-content="<div class='lead text-center'>
	 	{% trans 'Are you sure you want to delete this file?'%}</div>
	 	<div class='text-center'>
	 	<a class='btn btn-primary' href='{% url 'shop:product_remove' product.id product.slug %}'>
	 	<span class='glyphicon glyphicon-ok'></span>
	 	</a>
	 	<a class='btn btn-danger' onclick='$(this).parent().hide();'>
	 	<span class='glyphicon glyphicon-remove'></span>
	 	</a>
	 	</div>">
    	<span class="glyphicon glyphicon-trash"></span></button>
    	<!-- second -->
		<!-- <div class="popover-markup"> 
		    <a class="trigger btn btn-primary"><span class="glyphicon glyphicon-trash"></span></a>
		    <div class="content hide">
		      <div class="lead text-center">
		        {% trans 'Are you sure you want to delete this file?'%}
		      </div>
		      <div class="text-center">
			    <a class="btn btn-danger" href="{% url 'shop:product_remove' product.id product.slug %}"><span class="glyphicon glyphicon-remove"></span></a>
			    <a class="btn btn-primary"  href="{% url 'shop:product_edit' product.id product.slug %}"><span class="glyphicon glyphicon-ok"></span></a>	
			  </div>
		    </div>
		</div> -->
	 </div>
	<div class=" text-right col-md-4 col-md-offset-4" style="float: right;">
	  <span class="count">
		<span class="total">{{ total_views }}</span>
		{% trans 'View'%}{{ total_views|pluralize }}
	  </span>
	</div>
	 </br></br>
	 {% endif %}
	<div class="col-md-offset-6">
	  <form class="form-inline" style="float: right;" action="{% url 'cart:cart_add' product.id%}" method="post">
		<div class="form-group  ">
			{% crispy cart_form %}
		</div>					
	  </form>
	</div>	
</div>		

<hr class="custom">	
<div class="container-fluid">
  <div id="author-accordion">
	<div class="no-padding panel-group" id="accordion">
	  <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2 ">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
		      <h4 class="lead panel-title text-center"> {% trans 'Handcrafted by:'%}{{craftsman.get_full_name }} 	
		      </h4>
		    </a>
		  </div>
		  <div id="collapse1" class="panel-collapse collapse">
		    <div class="panel-body text-center">
		      <h3 style="font-family:Lobster;" ><font color="black">{{craftsman.get_short_name }}</font></h3>
		      	<img data-toggle="popover"  data-placement="auto bottom" data-content=" <blockquote class='lead' >{% if craftsman.bio%}{{ craftsman.bio }}{% else%}{% trans 'I invite you to see my profile '%}{% endif %}</blockquote> " title=" <h4><a href='{% url 'profiles:show' craftsman.slug %}'>{{craftsman.get_short_name }}</a></h4>" class="img-circle img-responsive img-thumbnail" src="{% thumbnail craftsman.picture|default:'default_profile.png' 150x150 crop %}"> 
		    </div>
		  </div>
		</div>
	  </div>  
	</div>
  </div>
  
  <div id="description-accordion">      
 	<div class="no-padding panel-group center-block" id="accordion" >
	  <div class=" col-xs-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-1">
	    <div class=" panel panel-default">
	      <div class="panel-heading">
	        <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
	          <h4 class="panel-title text-center">
	          {% trans 'Description:'%}
	          </h4>
	        </a>
	   	  </div>
	      <div id="collapse2" class="collapse collapse">
	      	<div class="panel-body">
	      	  <h3  style="font-family:Lobster;" ><font color="black">{{ product.name }}</font></h3>
	      		<p class="lead">{{product.description}}</p>    		
	      	</div>
	      </div>
	 	</div>
	  </div>  
  	</div>
  </div>
</div> 


{% endblock container %}


{% block scripts %}
<script src="https://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<script src = "{%static 'site/js/jquery.justifiedGallery.js' %}"></script>
<script>
    $("#detail").justifiedGallery({
    rowHeight : 350,
    lastRow : 'justify',    
    // nojustify or hide for last image
    margins : 10
    });
</script>
<script>
	$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
	});
</script>
<script>
	$("[data-toggle=popover]")
	.popover({html:true})
</script>
 <script>
  $('.popover-markup>.trigger').popover({
    html: true,
    title: function () {
        return $(this).parent().find('.head').html();
    },
    content: function () {
        return $(this).parent().find('.content').html();
    }
});
  </script>
<script>
	function close_please() {
    $('#meddelanden').popover('hide');
}
</script>
{% endblock scripts %}

socialhand/src/shop/templates/shop/product/list.html
{% extends "shop/home.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load el_pagination_tags %}

{% block title %} 
		{% if category %}
			{{ block.super }}{{ category.name }}
		{% else %}
			{{ block.super }} {% trans 'Products' %}
		{% endif %}
{% endblock %}

	{% block content %}
    
        <div class="container-fluid">
            <div class="col-lg-12">
                <h4 class="text-center"> 
                    {% trans 'Handcrafted things' %}
                </h4>
            </div>
        </div>
<!-- {% for product  in products %}
  {% if product.category == category %} 
    -{{ product.name }}.
    {{ product.category }}-    
    {%else %}  
    {%if not category %}         
         /{{ product.name }}.
            {{ product.category }}/  
            {% endif%}
    {% endif%}   
{% endfor %} -->
   
<div id="categories" class="container-fluid">
    <div class="btn-group btn-group-lg dropdown-menu">
    <button  class="btn-default btn-lg dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% if category.name %}{{ category.name }}{% else %}{% trans 'Categories'%}{% endif %}<span class="caret "></span></button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}" class=" ">{% trans 'All' %}</a>
            </li>
            <li class="divider"></li>
        {% for category in categories %} 
            <li {% if category.slug == category.slug %}{% endif %}>
                <a tabindex="-1" href="{{ category.get_absolute_url }}" class="product-category">{{ category.name }}</a>
            </li>
        {% endfor %}
            <!-- <li class="divider"></li>
            <li><a tabindex="-1" href="#">Other</a></li> -->
        </ul>
    </div>
 </div>     
     
<div id="pagination" class="endless_page_template">
        {% include "shop/product_list.html" %}
</div>
    	
{% endblock  %}


{% block scripts %}
<script src="{% static 'site/js/jquery.js' %}" ></script>
<script src="{% static 'site/js/el-pagination.js' %}"></script>
<script src="{% static 'site/js/el-pagination-endless.js' %}"></script> 
<script>$.endlessPaginate({paginateOnScroll: true});
</script>
<script >$(function(){ 
  $(".dropdown-menu li a").click(function(){   
    $(".btn:first-child").text($(this).text());
     $(".btn:first-child").val($(this).text());
  });});
</script>

{% endblock scripts %}

socialhand/src/shop/templates/shop/product/ranking.html
{% extends "shop/home.html" %}
{% load staticfiles %}
{% load thumbnail %}



{% block title %}Product ranking{% endblock %}

{% block content %}
	<h2>Product ranking</h2>
	<ol>
	{% for product in most_viewed %}
		<li>
		<a href="{{ product.get_absolute_url }}">
		{{ product.name }}
		</a>
		</li>
	{% endfor %}
	</ol>
{% endblock %}